// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// doLARS2D
List doLARS2D(SEXP R_Y, SEXP R_maxBreaks, SEXP R_maxVar, SEXP R_verbose, SEXP R_Beta);
RcppExport SEXP _blockseg_doLARS2D(SEXP R_YSEXP, SEXP R_maxBreaksSEXP, SEXP R_maxVarSEXP, SEXP R_verboseSEXP, SEXP R_BetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type R_Y(R_YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_maxBreaks(R_maxBreaksSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_maxVar(R_maxVarSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_verbose(R_verboseSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_Beta(R_BetaSEXP);
    rcpp_result_gen = Rcpp::wrap(doLARS2D(R_Y, R_maxBreaks, R_maxVar, R_verbose, R_Beta));
    return rcpp_result_gen;
END_RCPP
}
// Xprod
NumericVector Xprod(SEXP R_Y);
RcppExport SEXP _blockseg_Xprod(SEXP R_YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type R_Y(R_YSEXP);
    rcpp_result_gen = Rcpp::wrap(Xprod(R_Y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_blockseg_doLARS2D", (DL_FUNC) &_blockseg_doLARS2D, 5},
    {"_blockseg_Xprod", (DL_FUNC) &_blockseg_Xprod, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_blockseg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
