# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doLARS2D <- function(R_Y, R_maxBreaks, R_maxVar, R_verbose, R_Beta) {
    .Call('_blockseg_doLARS2D', PACKAGE = 'blockseg', R_Y, R_maxBreaks, R_maxVar, R_verbose, R_Beta)
}

Xprod <- function(R_Y) {
    .Call('_blockseg_Xprod', PACKAGE = 'blockseg', R_Y)
}

